2301/edit subtasks/input add subtasks
sorincretescu/curly-octo-robot pull request #1
Opened 2023-07-06 07:25 UTC by andregeorgi

2023-07-06 11:52 UTC, aleneagu96 commented on src/views/todo/Todo.jsx
> +    setOpenEditModal(false);
Nu stiu daca are sens sa inchizi modalul dupa ce adaugi un subtask nou, in ideea in care ai vrea sa adaugi mai multe.

2023-07-06 12:48 UTC, sorincretescu requested changes

2023-07-06 12:48 UTC, sorincretescu commented on src/components/Modal/Modal.jsx
> +            handleAddNewSubtask(newSubtaskText);
It would be a lot cooler if you would set the newSubtaskText on "" inside the handleAddNewSubtask()

2023-07-06 12:48 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    setOpenEditModal(false);
Agreed

2023-07-06 12:48 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    const newSubtask = [...todos];
You mean "newTodos"

2023-07-06 12:48 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    if (!newSubtask[currentTodo].subtasks) {
I would check for "!newSubtask[currentTodo]?.subtasks?.length"

2023-07-07 05:37 UTC, sorincretescu approved these changes

2023-07-07 06:07 UTC, aleneagu96 approved these changes

2023-07-07 06:16 UTC, merged