created header component
sorincretescu/curly-octo-robot pull request #23
Opened 2023-08-21 09:21 UTC by andregeorgi

2023-08-21 09:27 UTC, sorincretescu requested changes

2023-08-21 09:27 UTC, sorincretescu commented on src/App.js
> +          element={
Does this have anything to do with the current feature?

2023-08-21 09:27 UTC, sorincretescu commented on src/views/login/LoginPage.jsx
> +      <Header text={t("btn_register")} />
It does not make sense to have the text for the register button as a prop to the Header component unless you can configure multiple buttons, in which case you'd pass an array that would contain objects with buttonText, buttonAction, buttonVariation etc.

2023-08-21 09:27 UTC, sorincretescu commented on src/views/login/LoginPage.jsx
> +      <Header text={t("btn_register")} />
Also, what will you do when it is going to contain 2 buttons? text1={t('some text')} text2={t(...)}? Also have in mind future usage of your components when developing

2023-08-21 12:43 UTC, aleneagu96 approved these changes

2023-08-22 09:51 UTC, sorincretescu approved these changes

2023-08-22 10:40 UTC, merged