2304/filter tasks/add searchbar
sorincretescu/curly-octo-robot pull request #4
Opened 2023-07-07 07:48 UTC by aleneagu96

2023-07-07 07:53 UTC, gl1tch009 commented on src/components/SearchBar/SearchBar.jsx
> +              onChange={handleChange}/>
Can be shortened to `onChange={(ev) => handleSearch(ev.target.value)}` if you want to remove the handleChange function

2023-07-07 07:55 UTC, sorincretescu commented on src/components/SearchBar/SearchBar.jsx
> +              onChange={handleChange}/>
Nah, leave it there, it was my request to use handler functions till they catch on

2023-07-07 10:25 UTC, andregeorgi approved these changes

2023-07-07 10:25 UTC, andregeorgi commented on src/views/todo/Todo.jsx
> +  const [searchedTodoListTodos, setsearchedTodoListTodos] = useState([]);
Optional: rename the setter from setsearchedTodoListTodos --> setSearchedTodoListTodos; this is to have consistency in the code.

2023-07-07 10:47 UTC, aleneagu96 commented on src/views/todo/Todo.jsx
> +  const [searchedTodoListTodos, setsearchedTodoListTodos] = useState([]);
changed it 😄

2023-07-07 10:57 UTC, andregeorgi approved these changes

2023-07-13 10:36 UTC, sorincretescu requested changes

2023-07-13 10:36 UTC, sorincretescu commented on src/components/SearchBar/SearchBar.jsx
> +import Input from "../Input/Input";
Should work with just "../Input

2023-07-13 10:36 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +import MenuItem from '@material-ui/core/MenuItem';
As an optional remark: you can import multiple components from the same package as follows: import { MenuItem, FormControl, Select } from "@material-ui/core"

2023-07-13 10:36 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    marginTop:10,
Please be careful with the way your code looks. Spacing is important and it shows seriousness.

2023-07-13 10:36 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    borderRadius:4,
Same here with the spacing

2023-07-13 10:36 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +  selectDropdown: {
Unless you are 100% sure you will use this className, please remove it as it is empty

2023-07-13 10:36 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    setTodos(DummyToDos);
This is not the way to go. Faster? Yes. Correct? No. This practically means that every time you reset the sorting, you will lose any todos that you might have added. Or you will regain the ones you deleted from the initial todos.

2023-07-13 10:36 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    setTodos(DummyToDos);
To make the point clearer: resetting sorting does not mean deleting all of your changes.

2023-07-13 10:36 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +        {selectedPriority === "" ? (
Should not be the case. You should have still had the same map as before and only change the state of the todos. Nothing else should change. We do not change the source of mapping, we sort the todos we have. This will make more sense when you will have a database connection and you will just refetch data based on a search. For now, keep a copy of the todo list array in order to be able to revert to it when the search is cleared and when the sorting has been reset and only change the todos array when you search or sort. So no more condition ? condition ? condition : another : something else: whatever pls XDXD

2023-07-14 09:08 UTC, aleneagu96 commented on src/components/SearchBar/SearchBar.jsx
> +import Input from "../Input/Input";
done

2023-07-14 09:09 UTC, aleneagu96 commented on src/views/todo/Todo.jsx
> +import MenuItem from '@material-ui/core/MenuItem';
done

2023-07-24 06:16 UTC, sorincretescu approved these changes

2023-07-24 09:17 UTC, merged