2303/edit subtasks/handle save subtasks
sorincretescu/curly-octo-robot pull request #5
Opened 2023-07-07 09:59 UTC by aleneagu96

2023-07-07 10:27 UTC, andregeorgi approved these changes

2023-07-13 10:43 UTC, sorincretescu requested changes
Please, when you solve comments, try to understand what and why is happening. Especially with suggestions.

2023-07-13 10:43 UTC, sorincretescu commented on src/components/Modal/Modal.jsx
> +
Wouldn't this look better without the useless new line? ^^

2023-07-13 10:43 UTC, sorincretescu commented on src/components/Modal/Modal.jsx
> +            value={subtaskText[index]}
Can you please explain this? Where is it coming from? I see no "subtaskText".

2023-07-13 10:43 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    newTodos[currentTodo].subtasks = editedSubtasks;
Another way of writing this would be newTodos[currentTodo] = { priority, description, subtasks: editedSubtasks };

2023-07-14 08:21 UTC, aleneagu96 commented on src/components/Modal/Modal.jsx
> +
done

2023-07-14 08:23 UTC, aleneagu96 commented on src/views/todo/Todo.jsx
> +    newTodos[currentTodo].subtasks = editedSubtasks;
done

2023-07-20 09:44 UTC, andregeorgi approved these changes

2023-07-24 06:14 UTC, sorincretescu approved these changes

2023-07-24 09:17 UTC, merged