2306/react router/login screen
sorincretescu/curly-octo-robot pull request #6
Opened 2023-07-07 10:06 UTC by andregeorgi

2023-07-07 10:31 UTC, aleneagu96 approved these changes

2023-07-07 11:43 UTC, aleneagu96 approved these changes
PERFECT

2023-07-13 10:49 UTC, sorincretescu requested changes
As a general rule, a PR should only contain a feature or a set of feature that depend on each other / are connected in some way. Other than that, you have just a small change to do and you're good to go.

2023-07-13 10:49 UTC, sorincretescu commented on src/components/Modal/Modal.jsx
What do these changes have to do with the task?

2023-07-13 10:49 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +      if (!authenticated) return navigate("/");
This should not happen inside this page. It should happen on a higher level, namely where the routing is defined. This is prone to break.

2023-07-13 10:49 UTC, sorincretescu commented on src/views/todo/Todo.jsx
> +    const newTodos = [...todos];
As I've said before, what do these changes have to do with the current task? Did you make this branch out of another one instead of the main branch?

2023-07-14 05:26 UTC, sorincretescu approved these changes

2023-07-14 05:33 UTC, merged